#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_USRLOGIN                            100
#define DLG_ADDUSR                              101
#define DLG_EDITUSR                             102
#define IDD_MAINWND                             104
#define IDR_MAINMENU                            107
#define DLG_USRCNT                              109
#define IDR_STAFMENU                            111
#define DLG_SOLD                                113
#define DLG_ADDCLOTH                            115
#define DLG_EDITCLOTH                           117
#define DLG_STAT                                119
#define DLG_LOG                                 121
#define IDC_PWD1                                1000
#define IDC_BARCODE                             1001
#define IDC_ALLPRIV                             1002
#define IDC_TM                                  1002
#define IDC_CKIND                               1003
#define IDC_PNUM                                1004
#define IDC_PWD                                 1004
#define IDC_INVTR                               1005
#define IDC_USR                                 1005
#define IDC_CHK                                 1006
#define IDC_LSTCLT                              1006
#define IDC_PREPR                               1006
#define IDC_USRID                               1006
#define IDC_PERCENT                             1007
#define IDC_PURCHPR                             1007
#define IDC_BTNCALC                             1008
#define IDC_BTNSOLD                             1008
#define IDC_PRSLDPR                             1008
#define IDC_SLDPR                               1009
#define IDC_SOLDTIME                            1010
#define IDC_CID                                 1011
#define IDC_SOLDPER                             1011
#define IDC_SOLDNUM                             1012
#define IDC_BTNRET                              1015
#define IDC_BTNCHANGE                           1016
#define IDC_BTNADD                              1017
#define IDC_BTNEDIT                             1018
#define IDC_BTNDEL                              1019
#define IDM_USRCNT                              40000
#define IDM_EXIT                                40001
#define IDM_LOG                                 40002
#define IDM_STAT                                40003
#define IDC_LSTUSR                              40006
#define IDC_EDITUSR                             40010
#define IDC_ADDUSR                              40011
#define IDC_DELUSR                              40012
#define IDC_STATICSLDT                          40012
#define IDC_STATICSLDP                          40013
#define IDC_STATICPS                            40014
#define IDC_STATICPER                           40016
#define IDC_STATICSLDPR                         40017
#define IDC_MONSLD                              40019
#define IDC_MONINC                              40020
#define IDC_EDITYR                              40023
#define IDC_EDITMO                              40024
#define IDC_MONPROFIT                           40034
#define IDC_STREASON                            40034
#define IDC_REASON                              40036
#define IDC_LV                                  40038
#define IDC_BTNREASON                           40040
